### ISSUE TITLE
Error on onFinishedEventTrackingSucceeded

### ISSUE THREAD

**Issue by Fatimamostafa** [adjust/flutter_sdk#37] opened 2021-02-09 18:40 UTC
Regenration steps:

1. Launch app
2. Press back button, app gets destroyed
3. Relaunch app
4. Crashes on first Event Track

<img width="940" alt="Screen Shot 2021-02-10 at 12 37 38 AM" src="https://user-images.githubusercontent.com/20916180/107410993-323aff80-6b38-11eb-9947-d377e540c033.png">

**Comment by uerceg** [comment] 2021-02-09 18:45
Hi @Fatimamostafa 

Thanks for reporting and detailed steps to reproduce. Will be checked on our end as soon as possible. Will keep you posted.

**Comment by uerceg** [comment] 2021-02-12 00:46
Duplicate of https://github.com/adjust/flutter_sdk/issues/30.

**Closed by uerceg** 2021-02-12 00:46 UTC
