### ISSUE TITLE
invoke getXiaomiInstallReferrerDetails error: com.adjust.sdk.xiaomi.Util

### ISSUE THREAD

**Issue by WoojinGim** [adjust/flutter_sdk#96] opened 2022-10-27 01:55 UTC
version: 4.32.0

Hello,
On Android, Adjust.start() and Adjust.onResume() functions generate this error.
It seems to have no effect to execute our app, only just in case.

**Comment by uerceg** [comment] 2022-10-27 10:32
Hey @WoojinGim,

This is a duplicate of https://github.com/adjust/android_sdk/issues/558. Pretty much the same answer as written in that issue. Thanks for flagging and you can expect to see these error lines to disappear with next Flutter SDK update.

**Closed by uerceg** 2022-10-27 10:32 UTC
